### ISSUE TITLE
Failure running “Update Gutter” on save

### ISSUE THREAD

**Issue by fortin** [textmate/scm-diff-gutter.tmbundle#11]
On a fresh installation of TM 2.0.6, when I save a document (text file, in this case), I get this error:

```
Failure running “Update Gutter”.

Update Gutter:23:in `reset_marks': stack level too deep (SystemStackError)
	from Update Gutter:62:in `<main>'
```

Unsurprisingly, I don't get any errors if I disable Update Gutter. Any idea what could be causing this? Thanks.

**Comment by sorbits** [comment]
Go to Preferences → Software Update and switch to nightly builds and try with 2.0.15, I think there was some issue related to this that got fixed.

For future reference, please see https://macromates.com/support (opening issues on bundles is not the best channel to use for support)
