### ISSUE TITLE
Setting scmStatus = false no longer disables the gutter marks

### ISSUE THREAD

**Issue by savetheclocktower** [textmate/scm-diff-gutter.tmbundle#6]
Somehow, since the last update, I'm seeing SCM diff marks in my gutter even though I set `scmStatus = false` in my `~/.tm_properties` file.

I have no idea why, since a thorough inspection of the changelog doesn't seem to point to anything obvious, but it definitely started happening quite recently.

**Comment by sorbits** [comment]
This bundle does not use that setting. If you do not want diff markers in the gutter go to Preferences → Bundles and uncheck the SCM Diff Gutter item.

**Comment by savetheclocktower** [comment]
Ah, of course — that's for the file browser.

Consider this a feature request, then — it'd be nice if the bundle could be disabled on a per-project basis. On JavaScript projects I use the gutter to flag ESLint errors/warnings, but on other projects the SCM gutter marks would not be in the way.

**Comment by sorbits** [comment]
Something like this can be added to the top of the command:

	value = %x{"$TM_QUERY" 2>/dev/null -s scmStatus}
	exit if $? == 0 && value == 'disable'

This only disables it if `scmStatus` is set to `disable`, but this 
setting can also be set to `enableIfLocalDisk` and `enableIfSystemDisk` 
so maybe you will need to make the code more complex.

You can find TextMate’s logic here: 
https://github.com/textmate/textmate/blob/master/Frameworks/scm/src/scm.cc#L263

Feel free to submit a PR for this.

As for gutter marks eclipsing linter warnings, using gutter for warnings 
should be seen as a temporary solution :)

**Comment by savetheclocktower** [comment]
> As for gutter marks eclipsing linter warnings, using gutter for warnings
should be seen as a temporary solution :)

Agreed. Any way to control the order in which `did-save` callbacks run? I'd have to guarantee that the validation command ran last. :)

**Comment by sorbits** [comment]
There is no way to order the callbacks, we could add a number as the 
last component, e.g. callback.document.did-save.5 but I’m not exactly 
in love with this syntax.

Currently though TextMate will show marks with associated information 
above marks without, so I would think that your linter warnings would 
show over the SCM gutter marks, is this not the case?

**Comment by savetheclocktower** [comment]
The only information my linter warnings contain is the type of error. Is it now possible to associate information with gutter marks? I wasn't aware.

**Comment by sorbits** [comment]
Use the «value» part. Currently you have to click a mark to see the 
text.

	mate -h
	⋮
	 -s, --set-mark <mark>:<value> Set a mark containing <value> (requires 
--line).

**Comment by savetheclocktower** [comment]
Interesting. `mate -v` gave me a two-year-old version of the executable, and in that version I was able to set marks but not values. I figured it just symlinked to whatever was in the app bundle.

Uninstalling and reinstalling the shell integration gave me the ability to set messages, but added a new wrinkle: I can run (e.g.) `mate --line=1 --set-mark=error` from any shell, but it only actually does something if run it in `bash`. Running it from `zsh`, my primary shell, would bring TextMate to the front but wouldn't set the mark. (Not even Ruby's `system` method did the right thing, even though it uses `/bin/sh`, which is `bash`, at least on my machine.) If this isn't intended behavior, let me know and I'll happily file an issue on the main project.

Anyway, I had to change my bundle to run commands through `bash -c <command>` to get it to start working. But, yes, you're right: now the linting marks supersede the SCM marks. Thanks!

**Comment by sorbits** [comment]
From your bundle you should use "$TM_MATE" (not rely on `mate` from 
`PATH`).

TextMate would normally keep the installed `mate` updated, but it could 
fail if you reset settings, this is the logic used: 
https://github.com/textmate/textmate/blob/master/Frameworks/Preferences/src/TerminalPreferences.mm#L316

As for zsh etc., in your example you call `mate` without any file 
argument, are you doing this from a terminal? If so, this should not 
work in any shell.

If you are running from within TextMate, `mate` would find the 
`TM_DOCUMENT_UUID` environment variable and use that as the document to 
target.

If you take special steps to run your command from TextMate via zsh and 
do not provide a filename, it sounds like you are losing the environment 
given to the original process.

**Comment by savetheclocktower** [comment]
> From your bundle you should use "$TM_MATE" (not rely on `mate` from `PATH`).

That's what I'm doing:

```ruby
MATE = ENV['TM_MATE']
# ...
system(MATE, *args)
```
> As for zsh etc., in your example you call `mate` without any file argument, are you doing this from a terminal? If so, this should not work in any shell.

Ever have a day where the computers decide to play really mean jokes on you?

For whatever reason, I can't reproduce any of what I just reported. Even scrolling up in my shell history and running the exact same commands I ran earlier (many of which included the file path) is now working. I feel like [Michigan J. Frog's owner](https://en.wikipedia.org/wiki/Michigan_J._Frog).
