### ISSUE TITLE
Can't save file : error regarding updating the gutter

### ISSUE THREAD

**Issue by nicolinuxfr** [textmate/scm-diff-gutter.tmbundle#7]
When I try to save some files in a project, I have this error : 

```
Update Gutter:38:in `block in <main>': invalid byte sequence in UTF-8 (ArgumentError)
    from Update Gutter:35:in `open'
    from Update Gutter:35:in `<main>'
```

I tried to look into the code and it relates to end of lines. I don't know why exactly, and it's not consistent. Sometimes, after a commit, I can edit some files without problems but one of the files in my project display the same error…

In this project, I have mainly applescript files. Maybe it's related to the issue ?

Let me know if you need more information.

**Comment by sorbits** [comment]
Based on the error, it sounds like malformed UTF-8 gets output by `git diff …`, presumably because you have files with some other encoding?

Would be useful to get a copy of the file that triggers this issue, if it is sensitive, you can send it to tm-support(at)macromates.com.

I suggest you compress the file to avoid potential transcoding.

**Comment by nicolinuxfr** [comment]
I have a feeling it's an issue between TextMate and the AppleScript Editor from Apple. I converted the files into UTF-8 and not opened the editor since then, and it seems to work.

If I see the error again, I'll send a sample file !

Thanks for your answer :-)

**Comment by TrevorSayre** [comment]
I getting the same error with a file in a local git repo. I believe it was originally created on a Windows machine. It's a text file, php, and asks for the encoding upon opening. When trying to make  a change and saving out, I get:

```
Update Gutter:38:in `block in <main>': invalid byte sequence in UTF-8 (ArgumentError)
	from Update Gutter:35:in `open'
	from Update Gutter:35:in `<main>'
```

**Comment by infininight** [comment]
This has now been corrected with @noniq help, the bundle in TextMate will update within a few hours.
